spreing:
  message:
   basename: i18n\questions_answer

questions:
  count: 5 #количество вопросов
  path: C:\Users\User\Documents\GitHub\homework\src\main\resources\i18n\questions_answer_${localization}.csv #путь к CSV

localization: EN #локализация
#Есть две
#RU и EN