spring:
  messages:
    basename: i18n/messages
  main:
    lazy-initialization: true

questions:
  path:
    RU: src\main\resources\questions\questions_answer_RU.csv
    EN: src\main\resources\questions\questions_answer_EN.csv
  #путь к CSV